### ISSUE TITLE
On Loading World - "Value 20 exceeds the range!"

### ISSUE THREAD

**Issue by HiggsInc** [ClearSkyTeam/PocketMine-MP#46]
Creative World will not load. The following error comes up:
Error: Value 20 exceeds the range!
File: /src/pocketmine/entity/Attribute
Line: 176
Type: notice
Please refer to crashdump.

I've tried deleting players folder. The world still fails to load

* PocketMine-MP:ClearSky-PocketMine-MP 1.6.2dev 「Aurora」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.3.0 (protocol version 101)
* PHP: 7
* Server OS: CentOS 6.8
* Game version: PE/Win10
[Tue_Feb_28-12.35.22-CET_2017.log.zip](https://github.com/ClearSkyTeam/PocketMine-MP/files/806674/Tue_Feb_28-12.35.22-CET_2017.log.zip)

[Tue_Feb_28-12.35.22-CET_2017.log.zip](https://github.com/ClearSkyTeam/PocketMine-MP/files/806782/Tue_Feb_28-12.35.22-CET_2017.log.zip)

**Comment by thebigsmileXD** [comment]
@HiggsInc are you having slapper?

**Comment by HiggsInc** [comment]
@thebigsmileXD no I removed slapper a few months ago cause it had been creating an with a genisys install. Worked fine after the removal

**Comment by thebigsmileXD** [comment]
Some entity corrupted. I wonder how though. I tried effects, health change plugins, etc. I am sure its either some plugin problem or "overpowered" player.

**Comment by HiggsInc** [comment]
I would lean towards "overpowered" player. I took the corrupted world and used another pocketmine provider which produced no errors or crashdumps. Not sure if this helps but I've taken a screenshot of the effected chunks.


https://drive.google.com/open?id=0BxUmMLbp1c7AeElzNVA5WVJFaFk

**Comment by thebigsmileXD** [comment]
Oh right, should be fixed now

**Comment by HiggsInc** [comment]
This problem still exists however i may have found why it turns up. 
Firstly, if you have previously used tesseract/genisys and moving over to Clearsky, Worlds with entitys will encounter this error.  You will find that when a user moves towards areas with mobs, the server will crash.

PocketMine-MP version: 1.6.2dev #0 [Protocol 105; API 3.0.0-ALPHA4]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Workstation 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64
PHP Version: 7.0.6
Zend version: 3.0.0
OS : Linux, linux

**Comment by thebigsmileXD** [comment]
It should not crash though. Maybe Genisys & TerreREKT servers have wrong maxhealth for entities
